line_length:
  warning: 150
  error: 180

disabled_rules:
- todo
- multiple_closures_with_trailing_closure
- trailing_whitespace

identifier_name:
  min_length: 2
  allowed_symbols: "_"
  excluded:
    - _id

